# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital
# SPDX-License-Identifier: MIT

name: Setup Node.js
description: Setup the node.js environment

inputs:
  npm-token:
    description: 'The NPM token to use for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: npm
        write-mode: append
    - name: Install Dependencies
      shell: bash
      id: npm-ci
      run: npm ci
