# SPDX-FileCopyrightText: 2024 Telef贸nica Innovaci贸n Digital and contributors
# SPDX-License-Identifier: Apache-2.0

name: 'Check License Headers'
description: 'GitHub Action to check that all files have the correct license headers using the SPDX License Identifier'
author: 'Telef贸nica Innovaci贸n Digital'

# Define your inputs here.
inputs:
  config-file:
    description: 'Path to the configuration file'
    default: 'check-license-headers.config.yml'
  config:
    description: 'Configuration object expressed as a YAML string'
  log:
    description: 'Log level'
    type: choice
    options:
      - 'silly'
      - 'debug'
      - 'verbose'
      - 'info'
      - 'warn'
      - 'error'
      - 'silent'

runs:
  using: node20
  main: dist/index.js
