headers:
  - files:
      - "**/*.js"
      - "**/*.ts"
    license: "Apache-2.0"
  - files: "**/*.yml"
    license:
      - "MIT"
      - "Apache-2.0"
  - files: "**/node_modules/**"
    ignore: true
failOnError: false
reporter: "markdown"
log: "debug"
