# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

name: Test E2E

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      # NOTE: This checks the SPDX headers of the files in the repository with the real configuration
      - name: Check SPDX headers
        id: check-spdx-headers
        uses: ./

      # TODO: Add E2E tests, checking the output of different configurations
      # We could use a github-script action to parse the json report and check the results of each different configuration
